// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo98vmIAm3_67JwBtJ2MAReED29E1mkJ8',
    appId: '1:394931598204:web:edaa27d2b75d1117fdeaf9',
    messagingSenderId: '394931598204',
    projectId: 'expenses-c83c4',
    authDomain: 'expenses-c83c4.firebaseapp.com',
    storageBucket: 'expenses-c83c4.firebasestorage.app',
    measurementId: 'G-H7HPGB74FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqRsjedt4rJ2mQQbTBQvxi-zLv5zhNtc',
    appId: '1:394931598204:android:8f9eaf26ce94266ffdeaf9',
    messagingSenderId: '394931598204',
    projectId: 'expenses-c83c4',
    storageBucket: 'expenses-c83c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo97fOvZXcgf1cD0BZAsazh_WXT3-LBzo',
    appId: '1:394931598204:ios:020bc29cf39fc867fdeaf9',
    messagingSenderId: '394931598204',
    projectId: 'expenses-c83c4',
    storageBucket: 'expenses-c83c4.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo97fOvZXcgf1cD0BZAsazh_WXT3-LBzo',
    appId: '1:394931598204:ios:020bc29cf39fc867fdeaf9',
    messagingSenderId: '394931598204',
    projectId: 'expenses-c83c4',
    storageBucket: 'expenses-c83c4.firebasestorage.app',
    iosBundleId: 'com.example.expenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo98vmIAm3_67JwBtJ2MAReED29E1mkJ8',
    appId: '1:394931598204:web:a1c9131b4ba9e48dfdeaf9',
    messagingSenderId: '394931598204',
    projectId: 'expenses-c83c4',
    authDomain: 'expenses-c83c4.firebaseapp.com',
    storageBucket: 'expenses-c83c4.firebasestorage.app',
    measurementId: 'G-JEXN6S5C19',
  );
}
